/**
 * Manifest loading and indexing.
 *
 * The manifest is generated by the CMS at publish time from its link graph,
 * navigation and content model — nothing here is hand-authored per page.
 * See docs/INTERFACES.md for the contract this module consumes.
 */

import { normalizePath } from './util.js';

/** @typedef {Object} KaijuManifest */

let loadPromise = null;

/**
 * Fetch and index the manifest exactly once per page load.
 * @param {string} url
 * @returns {Promise<ReturnType<typeof index>>}
 */
export function loadManifest(url) {
  if (!loadPromise) {
    loadPromise = fetch(url, { credentials: 'same-origin' })
      .then((response) => {
        if (!response.ok) throw new Error(`manifest ${response.status} at ${url}`);
        return response.json();
      })
      .then((data) => index(data))
      .catch((error) => {
        loadPromise = null; // allow a later retry
        throw error;
      });
  }
  return loadPromise;
}

/** Build the lookup tables the tools query. */
export function index(manifest) {
  const pages = Array.isArray(manifest.pages) ? manifest.pages : [];
  const services = Array.isArray(manifest.services) ? manifest.services : [];
  const eligibility = Array.isArray(manifest.eligibility) ? manifest.eligibility : [];
  const forms = Array.isArray(manifest.forms) ? manifest.forms : [];
  const offices = Array.isArray(manifest.offices) ? manifest.offices : [];

  const pagesByPath = new Map();
  const pagesById = new Map();
  for (const page of pages) {
    pagesByPath.set(normalizePath(page.path), page);
    if (page.id) pagesById.set(String(page.id), page);
  }

  const servicesById = new Map(services.map((s) => [String(s.id), s]));
  const rulesetsById = new Map(eligibility.map((r) => [String(r.id), r]));
  const formsById = new Map(forms.map((f) => [String(f.id), f]));
  const officesById = new Map(offices.map((o) => [String(o.id), o]));

  return {
    raw: manifest,
    site: manifest.site || {},
    manifestVersion: manifest.manifestVersion || '0',
    generatedAt: manifest.generatedAt || null,
    pages, services, eligibility, forms, offices,

    /** Resolve a page by path, absolute URL, or manifest id. */
    page(ref) {
      if (!ref) return null;
      const key = String(ref);
      return pagesByPath.get(normalizePath(key)) || pagesById.get(key) || null;
    },

    /** Resolve a service by id, or fall back to a case-insensitive name match. */
    service(ref) {
      if (!ref) return null;
      const key = String(ref);
      const direct = servicesById.get(key);
      if (direct) return direct;
      const needle = key.toLowerCase().trim();
      return services.find((s) =>
        String(s.name || '').toLowerCase() === needle ||
        String(s.id || '').toLowerCase() === needle
      ) || services.find((s) => String(s.name || '').toLowerCase().includes(needle)) || null;
    },

    ruleset(ref) {
      if (!ref) return null;
      return rulesetsById.get(String(ref)) || null;
    },

    /** Resolve the ruleset a service points at. */
    rulesetForService(serviceId) {
      const service = servicesById.get(String(serviceId));
      if (!service || !service.eligibilityRulesetId) return null;
      return rulesetsById.get(String(service.eligibilityRulesetId)) || null;
    },

    form(ref) {
      if (!ref) return null;
      return formsById.get(String(ref)) || null;
    },

    /** Forms declared for a given page path. */
    formsForPath(path) {
      const key = normalizePath(path);
      return forms.filter((f) => normalizePath(f.path) === key);
    },

    office(ref) {
      if (!ref) return null;
      return officesById.get(String(ref)) || null;
    }
  };
}
